create table if not exists public.responses (id bigint generated by default as identity primary key, result text not null, time text not null, response_id bigint, created_at timestamptz not null default now());
create table if not exists public.commands (id bigint generated by default as identity primary key, command text not null check (char_length(command) between 1 and 2000), response_id bigint references public.responses(id), created_at timestamptz not null default now());
create index if not exists commands_pending_idx on public.commands (id) where response_id is null;
alter table public.commands enable row level security; alter table public.responses enable row level security;
drop policy if exists "anon insert commands" on public.commands; drop policy if exists "anon read commands" on public.commands; drop policy if exists "anon read responses" on public.responses;
create policy "anon insert commands" on public.commands for insert to anon with check (true); create policy "anon read commands" on public.commands for select to anon using (true); create policy "anon read responses" on public.responses for select to anon using (true);
